### ISSUE TITLE
ajouter des champs lors de "rejoindre le groupe syreen" pour compléter le profil

### ISSUE THREAD

**Issue by simonLouvet** [data-players/SyReen#102]

**Comment by simonLouvet** [comment]
- champs à ajouter sur Syreen et pas le POD
- suel les personne du groupe syreen peuvent voir les champs de profil B2B

**Comment by simonLouvet** [comment]
@pascal et @benoit fournissent les chanmps à ajouter

**Comment by simonLouvet** [comment]
Les personnes qui recoivent le mail doivent pouvoir consulter les champs remplis par l'utilisateur

**Comment by srosset81** [comment]
Toujours aucune nouvelle pour ces champs, après un mois d'attente.
Dommage qu'on n'arrive pas à tagger Benoit et Pascal. @simonLouvet

**Comment by srosset81** [comment]
Je n'ai pas réussi à trouver la raison pourquoi, sur des ancienx comptes, on n'arrive pas à obtenir le profil de l'acteur qui fait la demande. Mais plutôt que d'y passer plus de temps, j'ai amélioré la gestion d'erreur. Si cela échoue, un email sera quand même envoyé, ce qui permettra d'analyser le problème. Et peut-être qu'il ne se reproduira plus...
