### ISSUE TITLE
Ajouter la catégorie Batiprix sur le frontend

### ISSUE THREAD

**Issue by srosset81** [data-players/SyReen#109]

**Comment by srosset81** [comment]
Fait, tu vas pouvoir avancer: https://data.syreen.fr/batiprix

**Comment by VincentFarcy** [comment]
Hello @srosset81,
j'ai ajouté la catégorie basiquement pour le moment.
Les labels sont bizarres !
![image](https://github.com/data-players/SyReen/assets/55813208/e2cff252-9c76-4aaa-9367-1bb62789625e)

**Comment by srosset81** [comment]
Oui les labels sont obfusqués tant qu'on est pas passé sur leurs données de prod.
Je réouvre l'issue car il va falloir sans doute prévoir un affichage hiérarchique (à discuter cet après-midi).

**Comment by VincentFarcy** [comment]
@simonLouvet 
Petit rappel pour que tu mettes à disposition l'outil  de sélection basé sur une hiérarchie d'élément.
