### ISSUE TITLE
Affichage des offres: cout de revient et valeur de marché ne s'affichent pas malgré la publication

### ISSUE THREAD

**Issue by BenoitCier** [data-players/SyReen#110]
Les valeurs de cout de revient et de valeur de marché ne s'affichent pas sur les offres quand les valeurs sont marquées publiées.

**Comment by VincentFarcy** [comment]
Hello @srosset81 
les 2 booleans sont enregistrés bizarement : 
![image](https://github.com/data-players/SyReen/assets/55813208/50517f77-db1c-41b1-ac25-0876e0288990)
Vois-tu pourquoi ?

**Comment by srosset81** [comment]
C'est bizarre, dans le triplestore les données sont enregistrées correctement:

```turtle
<https://mypod.store/vincef/data/syreen/offers/647375baeb40fee6a0fc0478>
        a       <http://syreen.fr/ns/core#Offer> ;
        <http://syreen.fr/ns/core#partOf>
                <https://mypod.store/vincef/data/syreen/projects/64737595eb40fee6a0fc0477> ;
        <http://syreen.fr/ns/core#performancePercentage>
                60 ;
        <http://syreen.fr/ns/core#publishCostPrice>
                true ;
        <http://syreen.fr/ns/core#publishMarketValue>
                true ;
```

C'est le formatted en JSON-LD qui doit poser problème avec les boolean. Pourtant dans le fichier de context https://activitypods.org/context.json, cela semble correct

```json
"syreen:publishMarketValue": {
  "@type": "xsd:boolean"
},
"syreen:publishCostPrice": {
  "@type": "xsd:boolean"
},
```

**Comment by srosset81** [comment]
Je peux reproduire avec le playground JSON-LD:

https://json-ld.org/playground/?startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Factivitypods.org%2Fcontext.json%22%2C%22%40id%22%3A%22https%3A%2F%2Fmypod.store%2Fvincef%2Fdata%2Fsyreen%2Foffers%2F647375baeb40fee6a0fc0478%22%2C%22http%3A%2F%2Fsyreen.fr%2Fns%2Fcore%23performancePercentage%22%3A60%2C%22http%3A%2F%2Fsyreen.fr%2Fns%2Fcore%23publishCostPrice%22%3Atrue%2C%22http%3A%2F%2Fsyreen.fr%2Fns%2Fcore%23publishMarketValue%22%3Atrue%7D&context=%7B%22%40context%22%3A%22http%3A%2F%2Factivitypods.org%2Fcontext.json%22%7D

Il doit donc y avoir quelque chose de mal fait dans le context JSONLD d'ActivityPods, ou alors un bug qui est inhérent au format JSON-LD.

**Comment by srosset81** [comment]
Conclusion des tests: il suffit de supprimer:

```json
"syreen:publishMarketValue": {
  "@type": "xsd:boolean"
},
"syreen:publishCostPrice": {
  "@type": "xsd:boolean"
},
```

du context JSON et le compactage fonctionne bien. Les booleans sont visiblement un type natif, et le format JSON-LD le comprend sans qu'il y ait besoin de spécifier explicitement le type (comme les integer).

Je l'ai donc fait du context ActivityPods (http://activitypods.org/context.json)

@BenoitCier @VincentFarcy Je vous laisse réessayer, avec des données fraîches (je ne vais pas m'occuper de corriger les données de test)

**Comment by simonLouvet** [comment]
Benoit à tester et n'a pas réussi à le faire fonctionnner @VincentFarcy

**Comment by VincentFarcy** [comment]
Hello @srosset81  
j'ai toujours le même pb avec une nouvelle offre : 
![image](https://github.com/data-players/SyReen/assets/55813208/9e50cafc-42e6-4ce2-b618-5f4fece7fd43)

**Comment by srosset81** [comment]
Ah ça doit être parce que le `JsonLdService` sur mypod.store a gardé en cache le fichier de context. C'est source de bugs ça ! J'ai restarté mypod.store, je regarde si ça corrige le problème.

**Comment by srosset81** [comment]
C'est bon ça passe ! @VincentFarcy 

![Capture d’écran du 2023-06-26 10-37-59](https://github.com/data-players/SyReen/assets/17931931/d180e885-9fba-41eb-b150-ad28373cfc31)
