### ISSUE TITLE
L'image passe au-dessus des champs du sous-menu

### ISSUE THREAD

**Issue by srosset81** [data-players/SyReen#118]
![Image](https://github.com/data-players/SyReen/assets/17931931/5ae746a9-85fd-4621-8f46-489c4ac2142d)

**Comment by VincentFarcy** [comment]
Salut @srosset81 

De ce que je vois ça m'a l'air ok. La marge laisse bien la place à l'image et les champs qui débordent s'affichent sur la ligne suivante : 
![image](https://github.com/data-players/SyReen/assets/55813208/f7f68a7a-1943-4db5-83b4-83df910e8859)

Peux tu vérifier et  repréciser stp ?

**Comment by srosset81** [comment]
Ah OK, je ne pensais pas que c'était un comportement souhaité !
Perso j'aurai plutôt vu l'image en dessous, mais c'est une préférence.
Je ferme l'issue et Pascal ou Benoit recréeront une issue si besoin.
