### ISSUE TITLE
Pas accès à l'ensemble des catégories

### ISSUE THREAD

**Issue by GuillaumeAV** [data-players/SyReen#140]
Je souhaitais publier une annonce d'étagères, quand j'ai scrollé les catégories, je n'ai pu accéder à celles qui étaient après la lettre F - fluides frigorigènes .. 

Problème d'affichage j'imagine, @VincentFarcy je crois que c'est ta partie ?

**Comment by VincentFarcy** [comment]
Hello @GuillaumeAV 
C'est un champ autocomplete.
La liste que tu vois est une liste de suggestion qui évolue avec ta saisie.

**Comment by simonLouvet** [comment]
@GuillaumeAV est-ce que cette issue est résolue?

**Comment by GuillaumeAV** [comment]
Oui résolu, si ce n'est une petite amélioration UX pour les tanches de mon espèce ;) Mais pas nécessaire !
