### ISSUE TITLE
Le lot partagé à la personne destinatrice n’apparaît pas sur l'application

### ISSUE THREAD

**Issue by simonLouvet** [data-players/SyReen#22]

**Comment by srosset81** [comment]
Selon mes derniers tests, ça marche bien: les offres qui me sont partagées apparaissent sur la page d'accueil.
Par contre il faut attendre 2 minutes entre le partage et sa réception effective. C'est pour des raisons techniques, qui seront réglées lorsque l'architecture sera revue. J'imagine que ça a pu faire croire que le partage ne marchait pas... Pour l'utilisateur lamba, ce lag de 2 minutes ne se remarque pas pour autant.
