### ISSUE TITLE
Permettre de se déconnecter du pod en plus de l'application

### ISSUE THREAD

**Issue by simonLouvet** [data-players/SyReen#26]

**Comment by srosset81** [comment]
Proposer une connexion "globale" (c'est-à-dire sur toutes les applications où on est connecté) ne semble pas aisé.
Comme solution plus simple, je propose qu'après la déconnexion, on se retrouve sur son pod. On peut alors retourner à l'application ou se déconnecter du pod également.

**Comment by simonLouvet** [comment]
C'est ce type de comportement que nous avons mis en place sur app.essaipossible.fr
