### ISSUE TITLE
Bug sur la creation de projet et/ou d'offre a cause du cache

### ISSUE THREAD

**Issue by simonLouvet** [data-players/SyReen#27]

**Comment by BenoitCier** [comment]
Uniquement sur mon identifiant benoit2, cela fonctionne avec mon identifiant benoit

Bad Request au moment de la validation de l'offre, je pense que c'est le même genre de problématique que 

Impossible de créer un projet (bad request) #16

**Comment by srosset81** [comment]
Je me suis connecté en tant que "benoit2" et je ne reproduis pas, le projet et l'offre sont bien créés.

A mon avis ça a été réglé par le vidage du cache Redis...
