### ISSUE TITLE
Spécifier l'ergonomie des annonces pour mieux naviguer en fonction du degré de visibilité

### ISSUE THREAD

**Issue by simonLouvet** [data-players/SyReen#32]

**Comment by simonLouvet** [comment]
Intégré dans l'applciation principale

**Comment by simonLouvet** [comment]
Les maquettes à affiner pour rendre lisible / différencier la différence entre les données
- a soi
- partagé
- B2B
- Public

**Comment by simonLouvet** [comment]
un picto monde pour les offres publique.
Peut être un picto à trouver pour B2B Syreen

**Comment by srosset81** [comment]
https://v4.mui.com/components/material-icons/#material-icons
