### ISSUE TITLE
Adapter le formulaire de saisi d'offre

### ISSUE THREAD

**Issue by BenoitCier** [data-players/SyReen#49]
Travail de ce matin avec Tom sur les champs nécessaire dans les offres : 

https://pad.cier14.org/p/Formulaire_offre

**Comment by simonLouvet** [comment]
A finaliser par Benoit et Tom et transmetttre à Vincent une fois que c'est fiat

**Comment by VincentFarcy** [comment]
Version validée : https://pad.cier14.org/p/Formulaire_offre

**Comment by VincentFarcy** [comment]
Hello @srosset81,
j'ai avancé sur la branche https://github.com/data-players/SyReen/tree/49_adapter_le_formulaire_de_saisie_des_offres.
J'ai un soucis avec les booleanInput de react admin.

Exemple, avec ça en base :  
```
<https://mypod.store/vincef/data/offers/642dcdd060c64a515c24806a>
        a       <http://virtual-assembly.org/ontologies/pair-mp#Offer> ;
        <http://syreen.fr/ns/core#costPricePublication>
                true ;
        <http://syreen.fr/ns/core#marketValuePublication>
                true ;
```
J'obtiens ça dans mon navigateur :  
![image](https://user-images.githubusercontent.com/55813208/230196677-df5f57db-450e-4e61-814b-a231708a945d.png)
![image](https://user-images.githubusercontent.com/55813208/230196745-e7951f11-5228-420c-813f-74f0e1f16aac.png)


Je crois me rappeler que les boolean doivent être déclarés comme tels dans l'ontologie pour que ça fonctionne.  
Tu confirmes ?

**Comment by srosset81** [comment]
Très bizarre, j'ai jamais vu ça... 

J'ai ajouté les deux valeurs dans le fichier de context JSON https://activitypods.org/context.json, ça devrait être déployé d'ici à quelques minutes.

https://github.com/assemblee-virtuelle/activitypods/commit/3c80e206c2966fba03f1f14254a09c35758aaf1d

Mais je suis pas sûr que ce soit ça, car il semble que c'est bien enregistré comme boolean dans le triple store.

**Comment by VincentFarcy** [comment]
J'ai toujours le pb ce matin

**Comment by srosset81** [comment]
C'est peut-être parce que tu as aussi http://syreen.fr/ns/core#costPrice et http://syreen.fr/ns/core#marketValue. Le convertisseur JSON gère sans doute ça mal. Pas le temps de regarder plus aujourd'hui, je pourrai en début de semaine prochaine si besoin... mais a priori en utilisant un autre nom ça devrait passer.
D'ailleurs ce serait plus anglais http://syreen.fr/ns/core#publicationMarketValue non ? Pas sûr de comprendre à quoi correspond ce champ :-)

**Comment by VincentFarcy** [comment]
Ca fonctionne ;)
