### ISSUE TITLE
Modification des listes en dur, édition du code

### ISSUE THREAD

**Issue by BenoitCier** [data-players/SyReen#52]
C'est plus une question technique : 

La modification des listes en dur (comme le type sur la fiche projet) implique-t-elle une modification sur mypod.store?

Et ces conséquences : 

Et ce que je peux me permettre de modifier ce genre de liste moi-même (en concertation avec la partie concernée évidement), où dois-on forcément passé par seb et vincent?

Si possible de faire la modif moi-même, quel fonctionnement avec le dépôt ? (fourniture de patch, branch, fork, PR ...) 

P.S. : Cette réflexion peut s'appliquer à d'autre élément du code non technique (texte des formulaires,...)

**Comment by simonLouvet** [comment]
reformulation
qui peut modifier les listes de données.
les listes seront stockées dans un fichier json
Un importeur doit être mis en place pour synchroniser ces fichier de valeur avec le triplestore
