### ISSUE TITLE
Avoir une réflexion sur le livrable data-player

### ISSUE THREAD

**Issue by BenoitCier** [data-players/SyReen#53]
code+documentation vs application fonctionnelle

**Comment by simonLouvet** [comment]
l'essentiel est une aplicaiotn fonctionnelle. Nous pouvons fournir les shémas d'architecture et les informatiions essentielles pour la gestion de produciton.

**Comment by simonLouvet** [comment]
Benoit : besoin de doc sur les API LDP / SPARQL pour récupérer des données
