### ISSUE TITLE
Exportation des projets avec offres et photos

### ISSUE THREAD

**Issue by BenoitCier** [data-players/SyReen#58]
Ces fonctionnalités concernent plutôt les structures du réemploi que le particulier/artisan lambda

Comme on centralise les données sur la plateforme, autant pouvoir s'en servir pour générer les documents nécessaire à notre activité.

Quelque document envisager (liste amener a évoluer)
-diagnostic ressource de ce genre : https://document.cier14.org/s/9CQEsNRHgRt3MWp
-cerfa CSTB ou document d'aide au remplissage du cerfa
-bilan d'opération 
-convention de don Maitre d'ouvrage/structure réemploi

Quelque pistes:

-si manque de budget solution 1 accés par API, developpement outils maison, quid de la documentation?
-si manque de budget solution 2:  bouton export csv ou json, quid du traitement des photos ? archive avec photo nommée + json/csv

-Génération de documents sur la base de modèle fournit. quel format de sortie (pdf, odt), quid de l'évolution des documents

 -génération de documents sur la base de template libre avec un mécanisme de remplacement de "champs prédéfini" (voir dolibarr par exemple)

**Comment by simonLouvet** [comment]
A priori document lié à un projet et ses offres

**Comment by simonLouvet** [comment]
@BenoitCier quand tu parle d'archive, tu fais reference à un fichier compressé?

**Comment by srosset81** [comment]
## Solution sans archives et photos

React-Admin comprend un bouton qui permet d'exporter tous les éléments d'une liste ([voir doc](https://marmelab.com/react-admin/doc/3.19/Buttons.html#exportbutton))
Il suffirait de mettre un tel bouton sur la liste des projets.
Il faudrait aussi déréférencer les offres dans le tableau ([voir doc](https://marmelab.com/react-admin/doc/3.19/List.html#exporter)), sinon on aura qu'un URL par offre.
A voir sous quel format ça apparaîtrait dans le CSV. Je mettrai a priori une offre par ligne, en dupliquant les données du projets (qui sont finalement des méta données)
Il serait important de préciser la liste complète des champs attendus dans le fichier CSV.
Rien que ça peut prendre 1 jour si tout se passe bien comme indiqué dans la doc React-Admin.

## Solution avec archives et photos

Pour générer une archive avec le fichier CSV et les photos compressées, le mieux serait sans doute de le faire côté backend.
Ce qui est pas terrible, c'est que ça devrait être fait du côté du POD provider (bocage.me) ... et que si l'architecture évolue le code va être obsolète. Sinon donner les droits de lecture à un "bot" sur data.syreen.fr qui va lire les données. C'est globalement beaucoup de boulot, je dirais 3 jours à vue de nez.

**Comment by BenoitCier** [comment]
A priori, aucune des deux solutions ne me parait complètement satisfaisante...
Je pencherai plutôt pour la 1, mais pas d'accès aux photos...

Quelque précisions :

-C'est une fonctionnalité dont nous avons besoin aujourd'hui **en interne**, nous  n'avons pas forcément besoin que ce soient user friendly (en tout cas pour le moment, on vera ce qui est pertinent si on retrouve des sous pour financer des fonctionnalité), pas forcément besoin que ce soit intégrer à la plateforme.

Sans ça on va passer beaucoup de temps a faire de la double saisi de donnée (plateforme + diagnostic) dans le cadre de notre activité. C'est dommage sachant que le formulaire d'offre est pas mal pensé pour justement avoir les éléments nécessaire au diagnostic

-En creusant un peu, je suis sûr que tout ce dont on a besoin est disponible en réquetant directement le pod.

**Comment by srosset81** [comment]
> -C'est une fonctionnalité dont nous avons besoin aujourd'hui **en interne**, nous n'avons pas forcément besoin que ce soient user friendly (en tout cas pour le moment, on vera ce qui est pertinent si on retrouve des sous pour financer des fonctionnalité), pas forcément besoin que ce soit intégrer à la plateforme.

La solution 2 inclus seulement un endpoint API qu'on peut accéder avec un simple lien (p.ex. un bouton). Donc l'interface serait très basique de toute façon, le gros du travail serait côté backend.

> -En creusant un peu, je suis sûr que tout ce dont on a besoin est disponible en réquetant directement le pod.

Pour requêter directement un pod, il faut les droits pour ça. D'où l'idée de donner les droits de lecture à un "bot" qui serait sur data.syreen.fr (il faut que ce soit un acteur ActivityPub).

Si la solution 2 est retenue, je peux prendre un peu de temps pour approfondir et donner une estimation plus précise.

**Comment by srosset81** [comment]
Je vais estimer le temps précis pour solution 2

**Comment by BenoitCier** [comment]
Pour être sûr de comprendre :

Y a-t-il actuellement une API qui permette d'accéder au donné d'un pod?

**Comment by srosset81** [comment]
@BenoitCier Tu peux accéder aux données de ton Pod avec le token que tu récupères lors de la connexion. C'est comme ça que toutes les données sont récupérées sur l'appli Syreen. Mais ce token n'est pas censé circuler. Donc la solution proposée c'est de donner les droits à un bot, qui a ensuite la possibilité d'accéder à l'API du Pod.

**Comment by BenoitCier** [comment]
@srosset81 

> Donc la solution proposée c'est de donner les droits à un bot, qui a ensuite la possibilité d'accéder à l'API du Pod.

Cela me parait bien complexe tout ça.  J'ai commencé à creuser (sans succès pour le moment) en me basant sur https://github.com/assemblee-virtuelle/activitypods/blob/master/README.md 

De ce que je comprend je peut récuperer le token (/auth/login) puis acceder a toute mes offres (/data/offers)

**Comment by srosset81** [comment]
Il n'y a aucune complexité à donner le droit d'accès à un bot. De toute façon, le code qui va indexer les données et les photos, et les mettre dans un fichier zip, doit se situer au niveau de l'instance data.syreen.fr, ça ne peut pas être dans le Pod provider.

**Comment by BenoitCier** [comment]
J'ai réussi à comprendre la logique pour faire des requêtes sur mypod.store, du coup tant que Pascal ne trouve pas des sous, on peut se démerder de notre côté pour faire ce dont on a besoin.
