### ISSUE TITLE
Bug - la barre de recherche n'apparait que si un utilisateur nous a déjà partagé une offre

### ISSUE THREAD

**Issue by simonLouvet** [data-players/SyReen#72]

**Comment by VincentFarcy** [comment]
![image](https://user-images.githubusercontent.com/55813208/226193504-5db1c236-6971-410b-b3d7-bf71e428959d.png)

La barre de recherche est cachée par défaut et n'apparaît que si la liste est bien chargée (prop loaded=true), et si elle a du contenu (au moins une offre publique ou privée).  
Dans le cas contraire on affiche un message : "Aucune offre disponible actuellement".
