### ISSUE TITLE
Les partages ne sont pas gardé en mémoire ?

### ISSUE THREAD

**Issue by GuillaumeAV** [data-players/SyReen#75]
Je partage une offre à Benoit. 
Puis je partage plus tard la même offre à Pascal.
Quand je la partage à Pascal, je ne vois pas le bouton de partage activé pour Benoit. 

Si le bouton de partage était activé, ca me permettrait de savoir en temps réel, en direction de qui mes offres sont partagées ..

**Comment by VincentFarcy** [comment]
Bug non reproduit :  

https://user-images.githubusercontent.com/55813208/228836394-8b7a5c3f-a24c-46d2-a522-9412deb18b62.mp4  

J'ai ajouté un autre contact pour confirmer et les indicateurs de partage sont bien maintenus :  

![image](https://user-images.githubusercontent.com/55813208/228836633-de7c441e-96d6-460a-b5b7-d7f9c592c080.png)  

Peux-tu refaire le test @GuillaumeAV

**Comment by GuillaumeAV** [comment]
En effet ca marche, je n'ai pas reproduit non plus .. 
Une hypothèse : Je fais plein de choses trop vite en ce moment, je m'attendais peut-être à ce que quand le bouton est activé, il soit dans une couleur vive signifiant graphiquement "bouton allumé".
