### ISSUE TITLE
Voir les offres publiques sans être connecté 

### ISSUE THREAD

**Issue by GuillaumeAV** [data-players/SyReen#80]
Quand on est pas connecté, l'objectif serait d'arriver sur l'écran accueil actuel avec la liste des dernières offres publiques + possibilité de rechercher et de naviguer.
Il y aurait un bouton "Créer un compte" / "Se connecter" qui fait apparaître le menu du bas, et donne accès à l'ensemble de l'appli et des fonctionnalités. 
Ca n'a pas l'air de présenter de difficulté ou d'avoir d'impact sur le code selon Seb, juste de l'UX qui peut-être basique : 
- Arriver non pas sur une écran vide (l'interface d'inscription / connexion) comme à l'heure actuelle mais sur l'écran d'accueil
- Avoir un bouton "Se connecter" classique sauce React admin => être renvoyé sur l'interface d'inscription / connexion.
- Quand on clique cliquer l'un ou l'autre des 3 onglets Mes projets / Mon réseau / Mes alertes => être renvoyé sur l'interface d'inscription / connexion.

T'évaluerais à combien de temps @VincentFarcy ?

**Comment by VincentFarcy** [comment]
doublon avec https://github.com/data-players/SyReen/issues/67
