### ISSUE TITLE
Lorsqu'on partage une offre, donner aussi les droits acl:Read sur le projet

### ISSUE THREAD

**Issue by srosset81** [data-players/SyReen#82]
De même lorsqu'on rend une offre publique: rendre le projet public.

**Comment by VincentFarcy** [comment]
Idem pour les profils et localisations associés à ces projets ?

**Comment by srosset81** [comment]
Les profils non: si l'utilisateur n'est pas dans nos contacts, on ne verra que son username, mais pas son nom, ni sa photo.

Les localisations, c'est déjà fait dans l'Entraide mais il faut que je vois si ça marche pour les offres publiques aussi.

**Comment by srosset81** [comment]
Pour les offres, c'est fait ici: https://github.com/assemblee-virtuelle/activitypods/pull/50/commits/7ae2bec832e8061614d6043e776f7089b9f2e03d

**Comment by srosset81** [comment]
Et ici pour la localisation: https://github.com/assemblee-virtuelle/activitypods/pull/50/commits/fdec6a0f02389ead9d9a897e8af7faf4f680ef4d
C'est tout bon normalement ! Et déployé.
