### ISSUE TITLE
Utiliser une ontology syreen spécifique

### ISSUE THREAD

**Issue by srosset81** [data-players/SyReen#83]
Le fait d'utiliser l'ontologie PAIR marketplace créé des conflits avec l'application l'Entraide, notamment au niveau des notifications.

Il faudra attendre le refactoring qui extrait les "bots" pour avoir une solution durable.

En attendant, comme nous avons acté que pour ce MVP nous nous occuperons pas d'interopérabilité avec d'autres réseaux, je propose de tout passer sur une ontologie spécifique à Syreen (il y a d'ailleurs quelques éléments comme les quantités et les unités qui sont spécifiques à Syreen)

Ping @GuillaumeAV

**Comment by VincentFarcy** [comment]
@srosset81 je suppose que le pb existe aussi avec l'ontology mp (mp:offer).
Peux-tu confirmer ?

**Comment by VincentFarcy** [comment]
@GuillaumeAV voici les données actuellement utilisées pour intialiser l'ontology syreen : 
```
syreen:Project :
    'syreen:label': 'Titre',
    'syreen:alternativeLabel': 'Sous-titre',
    'syreen:depictedBy': 'Image',
    'syreen:description': 'Présentation',
    'syreen:hasLocation': 'Localisation',
    'syreen:locationInformation': 'Complément d\'adresse',
    'syreen:hasProjectType': "Type de projet",
    'syreen:startDate': "Date de début prévisionnelle",    
    'syreen:endDate': "Date de fin prévisionnelle"
```

```
syreen:Offer:
    'syreen:label': 'Titre',
    'syreen:depictedBy': 'Image',
    'syreen:description': 'Présentation',
    'syreen:hasLocation': 'Localisation',
    'syreen:locationInformation': 'Complément d\'adresse',
    'syreen:hasStage': 'Phase',
    'syreen:quantity': "Quantité",
    'syreen:hasUnit': "Unité",
    'syreen:partOf':"Fait partie du projet"
```

**Comment by srosset81** [comment]
J'ai terminé le travail côté backend, ça fonctionne bien en local. Il faudrait que je déploie sur mypod.store. Mais comme je pars en vacances lundi, et que @VincentFarcy va aussi être peu disponibles fin avril, je crois que c'est plus sûr d'attendre le 2 mai pour déployer...

**Comment by VincentFarcy** [comment]
Je pense qu'on peut clore cette issue (sans validayion MOA). @simonLouvet ?

**Comment by VincentFarcy** [comment]
Pour info @srosset81 je me suis aperçu que je n'avis pas terminé cette issue.
Je refais une passe demain.

**Comment by BenoitCier** [comment]
Dans une logique d'anticipation pour l'issue Action sur les offres : Scinder une offre #59, je me demande s'il ne serait pas intéressant d'avoir syreen:hasParent ou quelque chose du genre pour stocker l'offre d'origine. Je ne sais pas si c'est pertinent de l'intégrer maintenant ou si cela pourra être fait plus tard

**Comment by VincentFarcy** [comment]
L'ajouter sans la valoriser n'apportera rien.
On pourra l'ajouter le moment venu.
