### ISSUE TITLE
Erreur sur page projet

### ISSUE THREAD

**Issue by BenoitCier** [data-players/SyReen#97]
J'ai une erreur non blocante sur la page projet : 
Absolute IRI "syreen:locationInformation" confused with prefix "syreen".

**Comment by srosset81** [comment]
Je voulais parler de "syreen:locationInformation"

**Comment by srosset81** [comment]
Je peux faire la migration, mais si les données continuent d'être enregistrer incorrectement, l'erreur va se reproduire. Il faut donc s'assurer que ça ne soit plus le cas.

**Comment by VincentFarcy** [comment]
Ok il est bien toujours utilisé.
Il faut que je regarde pourquoi c'est enregistré en string

**Comment by srosset81** [comment]
Il faut que tu l'ajoutes dans le context https://activitypods.org/context.json
Voir ce qui a été fait ici: https://github.com/assemblee-virtuelle/activitypods/commit/b41554786f895ce9263fd5bcb59716d19462d54d

**Comment by VincentFarcy** [comment]
Salut @srosset81 , donc si je comprends bien, il faut que j'intervienne dans le repo activitypods pour mettre à jour les info concernant les données de l'ontologie Syreen. C'est bien ça ?

**Comment by VincentFarcy** [comment]
@srosset81 , J'ai refait le tour : 
```
string :
-    'syreen:label': 'Titre',
-    'syreen:alternativeLabel': 'Sous-titre',
-    'syreen:description': 'Présentation',
-    'syreen:locationInformation': 'Complément d\'adresse',

date :
-    'syreen:startDate': "Date de début prévisionnelle",    
-    'syreen:endDate': "Date de fin prévisionnelle"
-    'syreen:startDate': "Date prévisionnelle de disponibilité",

relation :
-    'syreen:hasProjectType': "Type de projet",
-    'syreen:hasStage': 'Phase',
-    'syreen:hasLocation': 'Localisation',
-    'syreen:hasCategory': "Categorie",
-    'syreen:hasUnit': "Unité",
-    'syreen:depictedBy': 'Image',
-    'syreen:hasPart'
-    'syreen:partOf'

numeric :
-    'syreen:quantity': "Quantité",
-    'syreen:sellingPrice': "Prix de vente",
-    'syreen:estimatedNewValue': "Valeur Neuve Estimée (€)",
-    'syreen:agePercentage': "Vétusté (%)",
-    'syreen:interestPercentage': "Intérêt (%)",
-    'syreen:performancePercentage': "Performance (%)",
-    'syreen:marketValue': "Valeur sur le marché",
-    'syreen:hourlyPrice': "Taux horaire (€)",
-    'syreen:dismantlingHours': "Nombre d'heures de démontage",
-    'syreen:collectionHours': "Nombre d'heures de collecte",
-    'syreen:refurbishmentAndSaleHours': "Nombre d'heures de reconditionnement/vente",
-    'syreen:additionalCosts': "Frais annexe pour le lot (Transport/Consommable) (€)",
-    'syreen:costPrice': "Coût de revient",

boolean
-    **'syreen:publishMarketValue': "Publier cette valeur",**
-    **'syreen:publishCostPrice': "Publier cette valeur",**

```
=> ok pour les relations
=> les booleans doivent être renommées
=> A voir pour les autres types de variable !

**Comment by simonLouvet** [comment]
@srosset81 & @VincentFarcy est ce que c'est résolu?

**Comment by VincentFarcy** [comment]
@simonLouvet
Je viens de tester avec un nouveau user de test : pour moi c'est ok on peut clore.
